name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  organization_name:
    description: "Current Organization Name"
    required: true
  repository_name:
    description: "Current Repository Name"
    required: true
  branch_name: 
    description: "Current Branch Name"
    required: true
    default: "main"
  sonarqube_project_key:
    description: "SonarQube Project Key"
    required: true

runs:
  using: "composite" 
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Maven Build
      if: inputs.branch_name == 'main' || inputs.branch_name == 'master'
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality

    - name: Maven Build -- Feature Branch
      if: inputs.branch_name != 'main' && inputs.branch_name != 'master'
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and analyze
      if: github.repository == '${inputs.organization_name}/${inputs.repository_name}'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${sonarqube_project_key}